services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: iot_edu
      MYSQL_USER: IoT_EDU
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    restart: unless-stopped

  backend:
    build: ./backend
    env_file: backend/.env
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
    restart: unless-stopped


  frontend:
    build: ./frontend
    env_file: backend/.env
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - backend
    restart: unless-stopped



  zeek-monitor:
    build: ./zeek-docker
    network_mode: host
    privileged: true
    environment:
      ZEEK_INTERFACE:  bridge-tap
    cap_add:
      - NET_RAW
      - NET_ADMIN
    volumes:
      - ./logs:/usr/local/zeek/spool/zeek
      - ./site:/usr/local/zeek/share/zeek/site
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

