"""
Django settings for sp_django project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import saml2
import saml2.saml

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$z!_uro6gzum-yc)eghg&xisy5_v8_p)sl%x@m_g_!7jfginy9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'backend.auth.base',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.auth.sp_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.auth.sp_django.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR.parent.parent / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configurações SAML2/CAFe
DOMAIN = "localhost"  # Ajustado para ambiente local
PORT = "8080"                   # Altere para sua porta
FQDN = "http://"+DOMAIN+":"+PORT
CERT_DIR = "certificates"

INSTALLED_APPS += [
    'djangosaml2',
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'djangosaml2.backends.Saml2Backend',
]

MIDDLEWARE.append('djangosaml2.middleware.SamlSessionMiddleware')

SAML_SESSION_COOKIE_NAME = 'saml_session'
SESSION_COOKIE_SECURE = True
LOGIN_URL = '/saml2/login/'
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SAML_DEFAULT_BINDING = saml2.BINDING_HTTP_POST
SAML_IGNORE_LOGOUT_ERRORS = True
SAML2_DISCO_URL = 'https://ds.cafeexpresso.rnp.br/WAYF.php'
SAML_CREATE_UNKNOWN_USER = True
LOGIN_REDIRECT_URL = '/users'

SAML_ATTRIBUTE_MAPPING = {
    'eduPersonPrincipalName': ('username', ),
    'mail': ('email', ),
    'givenName': ('first_name', ),
    'sn': ('last_name', ),
}

SAML_CSP_HANDLER = ''

SAML_CONFIG = {
    'xmlsec_binary': 'C:/Program Files/OpenSSL-Win64/bin/xmlsec1.exe',  # Ajuste o caminho se necessário
    'entityid': FQDN + '/saml2/metadata/',
    'attribute_map_dir': os.path.join(BASE_DIR, 'attribute-maps'),
    'description': 'SP Implicit',
    'service': {
        'sp': {
            'name': 'Exemplo SP Django',
            'ui_info': {
                'display_name': {'text':'SP Django Implicit', 'lang':'en'},
                'description': {'text':'Provedor de serviços Django Implicit', 'lang':'en'},
                'information_url': {'text':'http://sp.information.url/', 'lang':'en'},
                'privacy_statement_url': {'text':'http://sp.privacy.url/', 'lang':'en'}
            },
            'name_id_format': [
                "urn:oasis:names:tc:SAML:2.0:nameid-format:persistent",
                "urn:oasis:names:tc:SAML:2.0:nameid-format:transient",
            ],
            'endpoints': {
                'assertion_consumer_service': [
                    (FQDN +'/saml2/acs/', saml2.BINDING_HTTP_POST),
                ],
                'single_logout_service': [
                    (FQDN + '/saml2/ls/', saml2.BINDING_HTTP_REDIRECT),
                    (FQDN + '/saml2/ls/post', saml2.BINDING_HTTP_POST),
                ],
            },
            'signing_algorithm':  saml2.xmldsig.SIG_RSA_SHA256,
            'digest_algorithm':  saml2.xmldsig.DIGEST_SHA256,
            'force_authn': False,
            'name_id_format_allow_create': False,
            'want_response_signed': True,
            'authn_requests_signed': True,
            'want_assertions_signed': True,
            'only_use_keys_in_metadata': True,
            'allow_unsolicited': False,
        }
    },
    'metadata': {
        'remote': [{"url": "https://ds.cafeexpresso.rnp.br/metadata/ds-metadata.xml","cert": "null"}],
    },
    'debug': 1,
    'key_file': os.path.join(BASE_DIR, CERT_DIR, 'mykey.pem'),
    'cert_file': os.path.join(BASE_DIR, CERT_DIR, 'mycert.pem'),
    'encryption_keypairs': [{
        'key_file': os.path.join(BASE_DIR, CERT_DIR, 'mykey.pem'),
        'cert_file': os.path.join(BASE_DIR, CERT_DIR, 'mycert.pem'),
    }],
    'contact_person': [
        {'given_name': 'GIdLab', 'sur_name': 'Equipe', 'company': 'RNP', 'email_address': 'gidlab@rnp.br', 'contact_type': 'technical'},
    ],
    'organization': {
        'name': [('GIdLab', 'pt-br')],
        'display_name': [('GIdLab', 'pt-br')],
        'url': [('http://gidlab.rnp.br', 'pt-br')],
    },
}
